name = "Material-You"
bg = "Reset"
fg = "#bcc3ff"
border = "Rounded"
border_color = "#3b4279"
border_focused_color = "#bcc3ff"
hl_bg = "#0f0f0f"
solid_bg = "White"
solid_fg = "Black"
success = "Green"
error = "Red"
info = "Green"
warning = "Yellow"
